name: chatgpt_client
description: A sample ChatGPT client built with Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dart_openai: ^1.8.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  logging: ^1.2.0
  markdown_widget: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21